# Generated by Django 3.1.7 on 2021-03-18 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_bloguser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='profile_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img/%y'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='country',
            field=models.CharField(blank=True, choices=[('india', 'india')], max_length=50, null=True),
        ),
    ]
