# Generated by Django 3.1.7 on 2021-03-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210318_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='country',
            field=models.CharField(blank=True, choices=[('india', 'india'), ('japan', 'japan'), ('china', 'china')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='profile_image',
            field=models.ImageField(upload_to='media/%y'),
        ),
    ]
